name: Test-Tutorials

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          # In case of version change, update README.md accordingly
          node-version: 16
      - run: |
          npm ci
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          npx ts-node scripts/tutorial-runner.ts docs/zkapps/tutorials/01-hello-world.mdx

  deploying-network:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run tutorial
        env:
          USE_LOCAL_NETWORK: 'true'
        continue-on-error: false
        run: |
          npm ci
          npm run build --silent
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          npx ts-node scripts/tutorial-runner.ts docs/zkapps/tutorials/03-deploying-to-a-network.mdx
